// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfmiyfs4eRdPHqodCEksg3g1XQK3xHEs8',
    appId: '1:1074431678655:web:60775e0d640a18d65f4e0a',
    messagingSenderId: '1074431678655',
    projectId: 'logintest-f060a',
    authDomain: 'logintest-f060a.firebaseapp.com',
    storageBucket: 'logintest-f060a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapXRBwhyDrsNQA5WIqmrdpVKj8sE1F1E',
    appId: '1:1074431678655:android:76f97e837d23cf365f4e0a',
    messagingSenderId: '1074431678655',
    projectId: 'logintest-f060a',
    storageBucket: 'logintest-f060a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzrE-OPGGFsdUr_c_bFsifIP1m2KeFnk0',
    appId: '1:1074431678655:ios:715f47819d9a1c475f4e0a',
    messagingSenderId: '1074431678655',
    projectId: 'logintest-f060a',
    storageBucket: 'logintest-f060a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzrE-OPGGFsdUr_c_bFsifIP1m2KeFnk0',
    appId: '1:1074431678655:ios:715f47819d9a1c475f4e0a',
    messagingSenderId: '1074431678655',
    projectId: 'logintest-f060a',
    storageBucket: 'logintest-f060a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfmiyfs4eRdPHqodCEksg3g1XQK3xHEs8',
    appId: '1:1074431678655:web:3e8401f6401c4f5b5f4e0a',
    messagingSenderId: '1074431678655',
    projectId: 'logintest-f060a',
    authDomain: 'logintest-f060a.firebaseapp.com',
    storageBucket: 'logintest-f060a.firebasestorage.app',
  );
}